config/routes.rb
Store::Application.routes.draw do
  root to: 'home#index'

  resources :users
  resources :authors
  resources :books

  controller :search do
    post 'search' => :perform
  end

  controller :sessions do
    get  'login'  => :new
    post 'login'  => :create
    get  'logout' => :destroy
  end
end

app/models/author.rb
class Author < ActiveRecord::Base
  has_many :books

  default_scope :order => 'last_name ASC, first_name ASC'

  validates :first_name, :last_name, presence: true

  def to_s
    first_name + ' ' + last_name
  end

  def self.author_names(clear = false)
    if clear
      Rails.cache.delete(:author_names)
    end
    Rails.cache.fetch(:author_names) { Author.all.collect { |author| 'Author: ' + author.to_s } }
  end
end

app/models/book.rb
class Book < ActiveRecord::Base
  belongs_to :author

  validates :title, :isbn, presence: true
  validates :isbn, format: {
    with: /^ISBN\s((?=[-0-9xX ]{17}$)(?:[0-9]+[- ]){4}[0-9]*[xX0-9]|(?=[-0-9xX ]{13}$)(?:[0-9]+[- ]){3}[0-9]*[xX0-9])$/
  }
  validates :isbn, uniqueness: true

  def self.book_titles(clear = false)
    if clear
      Rails.cache.delete(:book_titles)
    end
    Rails.cache.fetch(:book_titles) { Book.all.collect { |book| 'Book: ' + book.title } }
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  validates :username, :name, presence: true
  validates :password, presence: true, on: :create
  validates :username, uniqueness: true
end

app/controllers/application_controller.rb
# All controllers should extend this file
# Provides common functionality for all controllers and requires user to login
# to all controllers by default
class ApplicationController < ActionController::Base
  protect_from_forgery

  before_filter :require_login

  protected

    # Checks that the user is logged and redirects to the login page if not
  	def require_login
      redirect_to login_path, notice: 'The requested action requires you to log in' unless session[:user_id]
    end
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  skip_before_filter :require_login, only: [:index, :show]
  cache_sweeper :author_sweeper

  def index
    @authors = Author.paginate(page: params[:page])
  end

  def show
    @author = Author.find(params[:id])
  end

  def edit
    @author = Author.find(params[:id])
  end

  def new
    @author = Author.new
  end

  def create
    @author = Author.new(
      first_name: params[:author][:first_name],
      last_name: params[:author][:last_name]
    )

    if @author.save
      redirect_to authors_path, notice: "#{@author} was successfully created"
    else
      render :new
    end
  end

  def update
    @author = Author.find(params[:id])

    if @author.update_attributes(params[:author])
      redirect_to @author, notice: "#{@author} was updated successfully"
    else
      render :edit
    end
  end

  def destroy
    author = Author.find(params[:id])
    author.destroy

    redirect_to authors_path, notice: "#{author} was successfully deleted"
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  skip_before_filter :require_login, only: [:index, :show]
  cache_sweeper :book_sweeper

  def index
    @author = Author.find(params[:author]) if params[:author] rescue nil
    if @author
      @books = @author.books.paginate(page: params[:page])
    else
      @books = Book.paginate(page: params[:page])
    end
  end

  def show
    @book = Book.find(params[:id])
  end

  def edit
    @book = Book.find(params[:id])
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(params[:book])

    if @book.save
      redirect_to books_path, notice: "#{@book.title} was successfully created"
    else
      render :new
    end
  end

  def update
    @book = Book.find(params[:id])

    if @book.update_attributes(params[:book])
      redirect_to @book, notice: "#{@book.title} was updated successfully"
    else
      render :new
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy

    redirect_to books_path, notice: "#{book.title} was successfully deleted"
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_filter :require_login
  def index
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  skip_before_filter :require_login

  def perform
    isbn = /^ISBN ((?=[-0-9xX ]{17}$)(?:[0-9]+[- ]){4}[0-9]*[xX0-9]|(?=[-0-9xX ]{13}$)(?:[0-9]+[- ]){3}[0-9]*[xX0-9])$/

    if isbn.match(params[:search])
      path = Book.find_by_isbn(params[:search])
    end

    unless path
      matches = /^(\w+): (.+)$/.match(params[:search])

      if matches && matches.length == 3
        type = matches[1]
        term = matches[2]

        case type
        when 'Book'
          path = Book.find_by_title(term)
        when 'Author'
          name = term.split(' ');
          path = Author.where("first_name = ?", name[0]).where("last_name = ?", name[1])[0] rescue nil
        end
      end
    end

    redirect_to path rescue redirect_to root_path, notice: 'Nothing found'
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_filter :require_login
  
  def new
  end

  def create
    user = User.find_by_username(params[:username])

    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path
    else
      redirect_to login_path, alert: 'Invalid username or password'
    end
  end

  def destroy
    session.delete(:user_id)
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_filter :require_login

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])

    if @user.save
      session[:user_id] = @user.id
      redirect_to @user, notice: 'User successfully created'
    else
      render :new
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def search_typeahead_datasource
    datasource = Book::book_titles + Author::author_names
    datasource.to_json
  end
end

app/helpers/author_helper.rb
module AuthorHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/authors/_author.html.slim
tr
  td= link_to author, author
  td= link_to author.books.count, books_path({author: author})
  td
    =link_to '', edit_author_path(author), class: 'icon-pencil'
    = link_to '', author, method: :delete, confirm: "Really delete author #{author}", class: 'icon-trash'

app/views/authors/_form.html.slim
= simple_form_for @author do |f|
  = f.input :first_name
  = f.input :last_name
  = f.button :submit

app/views/authors/_sidebar.html.slim
ul#author_nav.nav.nav-pills.nav-stacked
  li= link_to 'List Authors', authors_path
  li= link_to 'New Author', new_author_path

app/views/authors/edit.html.slim
.page-header
  h1
    | Edit Author
    small
      | Have you informed Depol?
= render 'form'

app/views/authors/index.html.slim
.page-header
  h1
    | Authors
    small 
      | Who's been writing stuff?

table.table.table-striped
  thead
    tr
      th Name
      th Books
      th
  tbody
    - @authors.each do |author|
      = render author

= will_paginate @authors

app/views/authors/new.html.slim
.page-header
  h1
    | New Author
    small 
      | What should we holler?
= render 'form'

app/views/authors/show.html.slim
.page-header
  h1
    = @author
    small
      = pluralize(@author.books.count, 'book')

table.table.striped
  thead
    tr
      th= "Books by #{@author}"
  tbody
    - @author.books.each do |book|
      tr
        td= link_to book.title, book

app/views/books/_book.html.slim
tr
  td= link_to book.title, book
  td= book.isbn
  td= link_to book.author, book.author
  td
    =link_to '', edit_book_path(book), class: 'icon-pencil'
    = link_to '', book, method: :delete, confirm: "Really delete book #{book.title}", class: 'icon-trash'

app/views/books/_form.html.slim
= simple_form_for @book do |f|
  = f.input :title
  = f.input :isbn, placeholder: 'ISBN 123-456-789-0'
  = f.input :synopsis, as: :text
  = f.association :author
  = f.button :submit, class: 'btn-primary'
  = link_to 'Cancel', books_path

app/views/books/_sidebar.html.slim
ul#author_nav.nav.nav-pills.nav-stacked
  li= link_to 'List Books', books_path
  li= link_to 'New Book', new_book_path

app/views/books/edit.html.slim
.page-header
  h1
    | Edit Book
    small
      | Made a mistake?
= render 'form'

app/views/books/index.html.slim
.page-header
  h1
    | Books
    small 
      = Author.find(params[:author]) rescue 'All authors'

table.table.table-striped
  thead
    tr
      th Title
      th ISBN
      th Author
      th
  tbody
    - @books.each do |book|
      = render book

= will_paginate @books

app/views/books/new.html.slim
.page-header
  h1
    | New Book
    small 
      | Write something!
= render 'form'

app/views/books/show.html.slim
.page-header
  h1
    = @book.title
    small= @book.author

app/views/layouts/application.html.slim
doctype html
html
  head
    title Store
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags

  body
    .navbar.navbar-fixed-top
      .navbar-inner
        .container

          a.btn.btn-navbar data-toggle="collapse" data-target=".nav-collapse"
            span.icon-bar
            span.icon-bar
            span.icon-bar

          a.brand Store

          .nav-collapse
            ul.nav
              li= link_to 'Home', root_path
              li= link_to 'Authors', authors_path
              li= link_to 'Books', books_path

          .nav-collapse
            ul.nav
              = form_tag search_path, class: 'navbar-search pull-left', autocomplete: :off do
                = text_field_tag :search, params[:search], class: 'search-query span2', placeholder: 'Search', %s{data-provide} => 'typeahead', %s{data-source} => search_typeahead_datasource

          .nav-collapse.pull-right
            ul.nav.pull-right
              li.dropdown
                - if session[:user_id]
                  a.dropdown-toggle href="#" data-toggle="dropdown"
                    = User.find(session[:user_id]).name
                    b.caret
                  ul.dropdown-menu
                    li= link_to 'Logout', logout_path
                - else
                  a.dropdown-toggle href="#" data-toggle="dropdown"
                    | Login
                    b.caret
                  ul.dropdown-menu= render 'sessions/form'
                  


    .container
      - if notice
        .alert.alert-info= notice
      - if alert
        .alert.alert-error= alert

      .row
        .span9
          .well= yield
        .span3
          #sidebar.well= render 'sidebar' rescue render 'home/sidebar'

app/views/users/_form.html.slim
= simple_form_for @user, html: { autocomplete: :off } do |f|
  = f.input :username
  = f.input :name
  = f.input :password
  = f.input :password_confirmation
  = f.button :submit

app/views/users/create.html.slim
h1 Users#create
p Find me in app/views/users/create.html.slim

app/views/users/new.html.slim
= render 'form'